swagger: "2.0"

info:
  version: 0.1.0
  title: prm - Package Server Web API
  description: API to query prm package and module specifications
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html

schemes:
  - http
host: cds-dc.cims.nyu.edu
#host: localhost:5000
basePath: /prm/package-server/api/v1

paths:
    #
    # Overview
    #
    /:
        get:
            summary: Service description
            description: Essential information about the web service and relevant links
            operationId: serviceOverview
            tags:
                - service
            produces:
                - application/json
            responses:
                200:
                    description: Service descriptor
                    schema:
                        $ref: '#/definitions/ServiceOverview'
    #
    # Packages
    #
    /packages:
        get:
            summary: List packages
            description: List all available packages with their description
            operationId: listPackages
            tags:
                - package
            produces:
              - application/json
            responses:
                200:
                    description: A list of package descriptors
                    schema:
                        type: object
                        required:
                            - packages
                            - links
                        properties:
                            projects:
                                type: array
                                items:
                                    $ref: "#/definitions/PackageDescriptor"
                            links:
                                type: array
                                items:
                                    $ref: '#/definitions/Reference'
    /packages/{packageQuery}:
        get:
            summary: Get modules
            description: Get module specifications that match the given package query
            operationId: getModules
            tags:
                - package
            parameters:
                - name: packageQuery
                  in: path
                  required: true
                  description: Package name prefix query
                  type: string
            responses:
                200:
                    description: List of matching module specifications
                    schema:
                        type: object
                        required:
                            - modules
                            - links
                        properties:
                            projects:
                                type: array
                                items:
                                    $ref: "#/definitions/ModuleSpecification"
                            links:
                                type: array
                                items:
                                    $ref: '#/definitions/Reference'
                404:
                    description: Unknown package
definitions:
    CommandComponent:
        type: object
        required:
            - type
            - value
        properties:
            type:
                type: string
            value:
                type: string
            varType:
                type: string
            asInput:
                type: boolean
    KeyValuePair:
        type: object
        description: Simple key-value pair
        required:
            - key
            - value
        properties:
            key:
                type: string
            value:
                type: string
    ModuleSpecification:
        type: object
        description: Module in VizUAL workflow
        required:
            - name
            - package
            - description
            - command
            - outputs
            - install
            - links
        properties:
            name:
                type: string
            package:
                type: object
                required:
                    - name
                    - subpath
                    - version
                properties:
                    name:
                        type: string
                    subpath:
                        type: string
                    version:
                        type: string
            description:
                type: string
            command:
                type: object
                required:
                    - type
                    - components
                properties:
                    type:
                        type: string
                    components:
                        type: array
                        items:
                            $ref: '#/definitions/CommandComponent'
            outputs:
                type: array
                items:
                    $ref: '#/definitions/OutputDescriptor'
            install:
                type: object
                required:
                    - tasks
                properties:
                    tasks:
                        type: array
                        items:
                            $ref: '#/definitions/TaskDescriptor'
            links:
                type: array
                items:
                    $ref: '#/definitions/Reference'
    OutputDescriptor:
        type: object
        description: Descriptor for an output resource generated by a module
        required:
            - name
            - location
            - format
        properties:
            name:
                type: string
            location:
                type: string
            format:
                type: object
                required:
                    - type
                properties:
                    type:
                        type: string
                    properties:
                        type: array
                        items:
                            $ref: "#/definitions/KeyValuePair"
    PackageDescriptor:
        type: object
        description: Fundamental project metadata and references
        required:
            - name
            - description
            - version
            - createdAt
            - lastModifiedAt
            - links
        properties:
            name:
                type: string
            description:
                type: string
            version:
                type: string
            createdAt:
                type: string
            lastModifiedAt:
                type: string
            links:
                type: array
                items:
                    $ref: "#/definitions/Reference"
    Reference:
        type: object
        description: "HATEOAS reference object"
        required:
            - rel
            - href
        properties:
            rel:
                type: string
            href:
                type: string
    ServiceOverview:
        type: object
        description: Basic service properties
        required:
            - name
            - title
            - links
        properties:
            name:
                type: string
            title:
                type: string
            links:
                type: array
                items:
                    $ref: "#/definitions/Reference"
    TaskDescriptor:
        type: object
        description: Descriptor for task in module install workflow
        required:
            - type
        properties:
            type:
                type: string
            properties:
                type: array
                items:
                    $ref: "#/definitions/KeyValuePair"
